spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://usersdb:5432/usersdb
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    consumer:
      group-id: ${kafka.consumer.groupId}
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.jzargo.messaging.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "com.jzargo.messaging.*"

kafka:
  consumer.groupId: user-group
  topic.names:
    debezium-flc: "pgserver.users.public.failed_leaderboard_creation"
    debezium-users: "pgserver.users.public.users"

application:
  headers:
    keycloak-connection:
      name: X-KEYCLOAK-SECRET
      value: Gz9Tj7cE2Rk1Q4L8aXnYhP7vWb3sQ6Lf
  images:
    dir-path:
      user: ../images/user
    dump:
      user: dump.png