spring:
  kafka:
    consumer:
      bootstrap-servers: kafka1:9090,kafka2:9092
    producer:
      bootstrap-servers: kafka1:9090,kafka2:9092
kafka:
  topic:
    insync-replicas: 2
    replicas: 2
    partitions: 3