spring:
  kafka:
    consumer:
      group-id: ${kafka.consumer.group-id}
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.jzargo.messaging.*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: 'com.jzargo.messaging.*'

application:
  db:
    name: scoresdb

kafka:
  consumer:
    group-id: scoring-group
  topic:
    names:
      debezium-scoring: "pgserver.public.scoring_events"
      debezium-failed: "pgserver.public.failed_create_leaderboard_events"
      debezium-deleted-event: "pgserver.public.deleted_events"
