name: leaderboard-lightweight

networks:
  config:
    driver: bridge
  tool:
    driver: bridge
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  vault-light-data:
    driver: local
  redpanda-data:
    driver: local

services:
  generaldb:
    build:
      context: ./postgres-init
    container_name: postgresdb
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root333
      POSTGRES_DATABASE: generaldb
    ports:
      - "5432:5432"
    networks:
      - tool
    volumes:
      - ./postgres-data:/bitnami/postgresql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: [
      "redis-server",
      "--requirepass", "redisPassword",
      "--appendonly", "yes"
    ]
    networks:
      - tool


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    depends_on:
      - generaldb
    container_name: keycloak
    command: start-dev
    mem_limit: 1024M
    networks:
      - tool
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin-password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://generaldb:5432/keycloakdb
      KC_DB_USERNAME: jzargo
      KC_DB_PASSWORD: root333
    ports:
      - "8899:8080"
    volumes:
      - ../keycloak-extensions/files:/opt/keycloak/providers
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    mem_limit: 1512M
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 1024M
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --set redpanda.auto_create_topics_enabled=true
      - --kafka-addr INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      - --advertise-kafka-addr INTERNAL://redpanda:29092,EXTERNAL://localhost:9092
    networks:
      - tool
    ports:
      - "9092:9092"
      - "9644:9644"

    volumes:
      - redpanda-data:/var/lib/redpanda/data

  debezium-dev-container:
    image: leaderboard-lightweight-debezium-dev-container:latest
    container_name: debezium-dev-container
    networks:
      - tool
    depends_on:
      - redpanda
      - generaldb
    environment:

      CONNECT_LOG4J_ROOT_LOGLEVEL: "DEBUG"
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.distributed=DEBUG,org.apache.kafka.clients=DEBUG"

      BOOTSTRAP_SERVERS: redpanda:29092
      GROUP_ID: "debezium-cluster"

      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-statuses

      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      KAFKA_OPTS: "-Xms512M -Xmx1G"
    mem_limit: 2G
  vault-light:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    privileged: true
    command: ["vault","server", "-config=/vault/config/vault-light.hcl"]
    volumes:
      - ./vault-config:/vault/config
      - vault-light-data:/vault/file
    networks:
      - config
  eureka:
    build:
      context: ./../EurekaServerService
    container_name: eureka-light
    networks:
      - backend
  gateway:
    build:
      context: ./../Gateway-api
    container_name: gateway
    networks:
      - backend
      - frontend
    ports:
      - "8080:8080"
  config-server-light:
    build:
      context: ./../ConfigServer
    networks:
      - backend
      - config