kafka:
  headers:
    message-id: "message-id"
    saga-id: "saga-id"

  topic:
    names:
      leaderboard-event: "leaderboard.user-activity.event"
      leaderboard-update: "leaderboard.state.updated"
      user-state-event: "user.state.event"
      saga-create-leaderboard: "leaderboard.create.saga"
      command-string-score: "event.user-score.command"
      participant-leaderboard: "leaderboard.participation.event"