server:
  port: 8888

spring:
  profiles:
    active: vault

  application:
    name: ConfigServer
  cloud:
    config:
      server:
        vault:
          port: ${VAULT_PORT}
          host: ${VAULT_HOST}
          authentication: APPROLE
          kv-version: ${KV_VERSION}
          scheme: http
          app-role:
            secret-id: "${VAULT_SECRET_ID}"
            role-id: "${VAULT_ROLE_ID}"
          backend: secret
          default-key: application
        native:
          search-locations:
            - file:///${CONFIG_DIR_PATH}/cloud/{application}/{profile}/
            - file:///${CONFIG_DIR_PATH}/cloud/{profile}/
            - file:///${CONFIG_DIR_PATH}/cloud
logging:
  level:
    org.springframework.cloud.config.server.environment.VaultEnvironmentRepository: TRACE
    org.springframework.web.client.RestTemplate: TRACE
    org.springframework.cloud.config.server: DEBUG
    org.springframework.cloud.vault: DEBUG
    org.springframework.web: DEBUG