spring:
  kafka:
    consumer:
      group-id: ${kafka.consumer.groupId}
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "com.jzargo.messaging,
        com.jzargo.leaderboardmicroservice.core.messaging"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "com.jzargo.messaging,
        com.jzargo.leaderboardmicroservice.core.messaging"
application:
  max.durationForInactiveState: 86400000
  proxy:
    mode:
      leaderboard: KAFKA
      scoring: KAFKA
      user: KAFKA

kafka:
  consumer:
    groupId: leaderboard-group