server:
  port: 8080

spring:
  datasource:
    username: jzargo
    password: root333
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://generaldb:5432/usersdb
  kafka:
    consumer:
      group-id: user-group
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.JsonDeserializer
        spring.json.trusted.packages: "com.jzargo.messaging.*"
      bootstrap-servers: kafka1:9090,kafka2:9090
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "com.jzargo.messaging.*"
      bootstrap-servers: kafka1:9090,kafka2:9090
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

kafka:
  topic:
    partition:
      insync-replicas: 2
      count: 3
    replicas: 2