server:
  port: 8081

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9090,localhost:9092
    producer:
      bootstrap-servers: localhost:9090,localhost:9092
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: users-api
            client-secret: UXVg0cDfPbksgd21MKJBHOxbr6JpDe3K
            authorization-grant-type: client_credentials
            scope: openid, profile
        provider:
          keycloak:
            issuer-uri: http://localhost:8899/realms/leaderboard-security
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8899/realms/leaderboard-security
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/