spring:
  application:
    name: UserMicroservice
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: users-api
            client-secret: UXVg0cDfPbksgd21MKJBHOxbr6JpDe3K
            authorization-grant-type: client_credentials
            scope: openid, profile
        provider:
          keycloak:
            issuer-uri: http://localhost:8899/realms/leaderboard-security
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8899/realms/leaderboard-security


api:
  keycloak-connection-header: X-KEYCLOAK-SECRET
  secret-keycloak-connection: Gz9Tj7cE2Rk1Q4L8aXnYhP7vWb3sQ6Lf
images:
  dir-path:
    user: ../images/user
  dump:
    user: dump.png