server:
  port: 0

spring:

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: jzargo
    password: root333
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://generaldb:5432/usersdb
  kafka:
    consumer:

      group-id: user-group
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.jzargo.messaging.*"

      bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "com.jzargo.messaging.*"

        bootstrap-servers: localhost:9092

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: users-api
            client-secret: UXVg0cDfPbksgd21MKJBHOxbr6JpDe3K
            authorization-grant-type: client_credentials
            scope: openid, profile
        provider:
          keycloak:
            issuer-uri: http://localhost:8899/realms/leaderboard-security
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8899/realms/leaderboard-security
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
kafka:
  topic:
    partition:
      insync-replicas: 1
      count: 1
    replicas: 1