spring:
  application:
    name: websocket-api-microservice
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
    include: ${SPRING_PROFILES_INCLUDE:}
  config:
    import: 'optional:configserver:${URL_CONFIG_SERVER}'
