kafka.topic.names:
  debezium-scoring: "pgserver.public.scoring_events"
  debezium-failed: "pgserver.public.failed_create_leaderboard_events"
  debezium-deleted-event: "pgserver.public.deleted_events"
