spring:
  profiles:
    active:  ${SPRING_PROFILES_ACTIVE:devconfig}
    include: ${SPRING_PROFILES_INCLUDE:}
  application:
    name: leaderboard-microservice
leaderboard:
  max:
    durationForInactiveState: 86400000
