server:
  port: 0


spring:
  profiles:
    group:
      "devconfig":
        - redis-common-{spring.profiles.active}
        - kafka-common-{spring.profiles.active}
        - eureka-common-{spring.profiles.active}
    active: devconfig
  application:
    name: leaderboard-microservice
  config:
    import: 'optional:configserver:http://localhost:8888'