server:
  port: 0

spring:
  data:
    redis:
      password: redisPassword
      port: 6379
      host: localhost
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: leaderboard-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "com.jzargo.messaging,
        com.jzargo.leaderboardmicroservice.core.messaging"
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "com.jzargo.messaging,com.jzargo.leaderboardmicroservice.core.messaging"
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: leaderboard
            client-secret: cKA0bJ3dVU62zMm3Pald5DU23zpg94vx
            authorization-grant-type: client_credentials
            scope: openid, profile
        provider:
          keycloak:
            issuer-uri: http://localhost:8899/realms/leaderboard-security
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8899/realms/leaderboard-security
kafka:
  topic:
    insync-replicas: 1
    replicas: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
