spring:
  profiles:
    active:  ${SPRING_PROFILES_ACTIVE:devconfig}
    include: ${SPRING_PROFILES_INCLUDE:}
  application:
    name: leaderboard-microservice

logging:
  level:
    org:
      springframework:
        expression: DEBUG
      kafka:
        annotation:
          KafkaListenerAnnotationBeanPostProcessor: TRACE