server:
  port: 8080

spring:
  data:
    redis:
      cluster:
        nodes:
          - redis-1:6379
          - redis-2:6379
      password: masterRedisPassword
  kafka:
    consumer:
      bootstrap-servers: kafka1:9090,kafka2:9092
      group-id: leaderboard-group
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "com.jzargo.messaging,
        com.jzargo.leaderboardmicroservice.core.messaging"
    producer:
      bootstrap-servers: kafka1:9090,kafka2:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "com.jzargo.messaging,
        com.jzargo.leaderboardmicroservice.core.messaging"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8899/realms/leaderboard-security
kafka:
    topic:
      insync-replicas: 2
      replicas: 2

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
